version: 2.1

# Set up the environment variables
# update the website
# make the homebrew zip folder
# make the changelog
# make the debian file
# update the readme
# pull the checksum version
# push the new checksum to the repo master branch

orbs:
  aws-cli: airswap/aws-cli@volatile

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  load_version: &load_version
    run:
      name: Load version from file
      command: |
        echo "export VERSION=0.9.2" >> $BASH_ENV

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - checkout:
          path: ~/repo
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  change_website:
    <<: *container_config
    steps:
      - *restore_repo
      - *load_version
      - run:
          name: Change the website
          command: |
            # version swap the website
            echo $VERSION
            echo $CIRCLE_TAG # use this instead as the version
            envsubst < website/index.template.html > website/index.html
            aws s3 sync ./website s3://aws-rotate-iam-keys.com --delete --acl public-read
            aws s3 cp ./Windows/aws-rotate-iam-keys.ps1 s3://aws-rotate-iam-keys.com/aws-rotate-iam-keys.ps1 --acl public-read

  build:
    <<: *container_config
    steps:
      - *restore_repo
      - *load_version
      - run:
          name: Build the .deb package for Bionic
          command: |
            # version swap the website
            echo $VERSION
            echo $CIRCLE_TAG # use this instead as the version
            sudo apt install devscripts
            # make the dist folder
            mkdir -p dist
            # copy in the src and swap the versions
            cp -r src/** dist/
            sed "s/<<VERSION>>/$VERSION/g" src/bin/aws-rotate-iam-keys > dist/bin/aws-rotate-iam-keys

            CHANGES="aws-rotate-iam-keys_$VERSION~bionic1_source.changes"
            # make the homebrew zip file
            zip -r aws-rotate-iam-keys_$VERSION.zip src

            cd dist

            # make the changelog
            #DEBEMAIL="Adam Link <aws-rotate-iam-keys@rhyeal.com>" DEBFULLNAME="Adam Link" dch -v $VERSION --distribution bionic --force-distribution

            #mv debian DEBIAN
            #envsubst < DEBIAN/control-debian > DEBIAN/control


  test:
    <<: *container_config
    steps:
      - *restore_repo

  release:
    <<: *container_config
    steps:
      - *restore_repo

workflows:
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          context: Personal_AWS
          requires:
            - checkout_code
      # - test:
      #     context: Personal_AWS
      #     requires:
      #       - build
      # - release:
      #     context: Personal_AWS
      #     requires:
      #       - test
      #     filters:
      #         tags:
      #           only: /^v.*/
      #         branches:
      #           ignore: /.*/
      - change_website:
          context: Personal_AWS
          # requires:
          #   - release
          filters:
            branches:
              only:
                - adding-ci
