version: 2.1

# Set up the environment variables
# update the website
# make the homebrew zip folder
# make the changelog
# make the debian file
# update the readme
# pull the checksum version
# push the new checksum to the repo master branch

orbs:
  aws-cli: airswap/aws-cli@volatile

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  load_version: &load_version
    run:
      name: Load version from file
      command: |
        echo "export VERSION=$(cat VERSION)" >> $BASH_ENV

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - checkout:
          path: ~/repo
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  change_website:
    <<: *container_config
    steps:
      - *restore_repo
      - *load_version
      - run:
          name: Change the website
          command: |
            # version swap the website
            echo $VERSION
            envsubst < website/index.template.html > website/index.html
            aws s3 sync ./website s3://aws-rotate-iam-keys.com --delete --acl public-read
            aws s3 cp ./Windows/aws-rotate-iam-keys.ps1 s3://aws-rotate-iam-keys.com/aws-rotate-iam-keys.ps1 --acl public-read

  build:
    <<: *container_config
    steps:
      - *restore_repo

  test:
    <<: *container_config
    steps:
      - *restore_repo

  release:
    <<: *container_config
    steps:
      - *restore_repo

workflows:
  build_and_deploy:
    jobs:
      - checkout_code
      # - build:
      #     context: Personal_AWS
      #     requires:
      #       - checkout_code
      # - test:
      #     context: Personal_AWS
      #     requires:
      #       - build
      # - release:
      #     context: Personal_AWS
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only:
      #           - adding-ci
      - change_website:
          context: Personal_AWS
          requires:
            - release
          filters:
            branches:
              only:
                - adding-ci
